version: "2.2"

volumes:
  postgres_data:
    driver: local

services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}-php
    build:
      context: ""
      dockerfile: php/Dockerfile-php
    volumes:
      - "../:/app"
      - "~/.ssh:/var/www/.ssh"
      - "${COMPOSER_CACHE}:/composer/cache"
      - "./php/php-fpm-www-pool.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "./php/php-fpm.conf:/usr/local/etc/php-fpm.conf"
      - "./php/php.ini:/usr/local/etc/php/php.ini"
    restart: always
    environment:
      - PHP_XDEBUG_IDEKEY=PSTORM
      - PHP_XDEBUG_MODE=develop
      - PHP_XDEBUG_DISCOVER_CLIENT_HOST=0
      - PHP_XDEBUG_CLIENT_HOST=host.docker.internal
      - PHP_XDEBUG_CLIENT_PORT=9003

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: always
    image: nginx:latest
    depends_on:
      - php
    ports:
      - "${NGINX_EXPOSE_PORT}:80"
    volumes:
      - "./nginx/logs:/var/log/nginx"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/default.template:/etc/nginx/conf.d/default.template"
      - "../:/app"
    environment:
      - NGINX_HOST=${COMPOSE_PROJECT_NAME}.local
      - NGINX_PORT=80
      - PHP_FPM_HOST=${COMPOSE_PROJECT_NAME}-php
      - PHP_FPM_PORT=9000
      - TZ=UTC
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    restart: always
    build:
      context: ""
      dockerfile: postgres/Dockerfile.postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_NAME=${COMPOSE_PROJECT_NAME}
    ports:
      - "${POSTGRES_EXPOSE_PORT}:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./postgres/init.d:/docker-entrypoint-initdb.d"
